"""empty message

Revision ID: 2a8c8ddb733c
Revises: 007daef60fbf
Create Date: 2022-10-03 17:14:03.156502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8c8ddb733c'
down_revision = '007daef60fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('language', sa.Enum('AR', 'DE', 'EN', 'ES', 'FA', 'FR', 'IT', 'JP', 'NL', 'PL', 'PT', 'RU', 'TR', 'VI', 'ZH', name='languages'), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('traveler', sa.Enum('Solo', 'Couple', 'Family', 'Group', name='travelertypes'), nullable=True),
    sa.Column('trip', sa.Enum('Backpack', 'Business', 'Camping', 'Caravan', 'Hiking', 'Mini', 'Package', 'Roadtrip', name='triptypes'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('language', sa.VARCHAR(length=2), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('traveler', sa.VARCHAR(length=6), nullable=True),
    sa.Column('trip', sa.VARCHAR(length=8), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('user', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('display_name', sa.VARCHAR(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
