"""initial_migration

Revision ID: 57de01745cbc
Revises: 
Create Date: 2023-01-15 16:26:49.942920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57de01745cbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('roles', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('language', sa.Enum('AR', 'DE', 'EN', 'ES', 'FA', 'FR', 'IT', 'JP', 'NL', 'PL', 'PT', 'RU', 'TR', 'VI', 'ZH', name='languages'), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('traveler', sa.Enum('Couple', 'Family', 'Friends', 'Group', 'Solo', name='travelertypes'), nullable=True),
    sa.Column('trip', sa.PickleType(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
