"""empty message

Revision ID: c6771c902f30
Revises: 2a8c8ddb733c
Create Date: 2022-10-04 17:06:17.995514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6771c902f30'
down_revision = '2a8c8ddb733c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('roles', sa.String(length=255), nullable=True))
    op.drop_column('users', 'admin')
    op.drop_column('users', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.BOOLEAN(), nullable=False))
    op.add_column('users', sa.Column('admin', sa.BOOLEAN(), nullable=False))
    op.drop_column('users', 'roles')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
