"""empty message

Revision ID: e8e0f55e921f
Revises: 
Create Date: 2022-10-03 14:58:19.946686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e0f55e921f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('language', sa.Enum('AR', 'DE', 'EN', 'ES', 'FA', 'FR', 'IT', 'JP', 'NL', 'PL', 'PT', 'RU', 'TR', 'VI', 'ZH', name='languages'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('traveler', sa.Enum('Solo', 'Couple', 'Family', 'Group', name='travelertypes'), nullable=True),
    sa.Column('trip', sa.Enum('Backpack', 'Business', 'Camping', 'Caravan', 'Hiking', 'Mini', 'Package', 'Roadtrip', name='triptypes'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('post')
    # ### end Alembic commands ###
