services:
  flask:
    build: flask-backend
    env_file:
      - flask-backend/.env
    expose:
      - 5000
    restart: always
  react:
    build: react-frontend
    ports:
      - 3000:80
    restart: always