services:
  flask:
    build: flask-backend
    env_file:
      - flask-backend/.env
    expose:
      - 5000
    restart: always
  react:
    build: react-frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ojones/certs:/etc/nginx/certs
    restart: always